#! /bin/sh

sxhkd &

bspc monitor -d $(echo -e '\uf109') $(echo -e '\uf268') $(echo -e '\uf120')  $(echo -e '\uf001') $(echo -e '\uf181') $(echo -e '\uf126')  $(echo -e '\uf008') $(echo -e '\uf1b6') $(echo -e '\uf085') $(echo -e '\uf1fc')

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#1e1e1e"
bspc config active_border_color "#2fd496"
bspc config focused_border_color "#2fd496"
bspc config presel_border_color "#ffffff"

bspc rule -a gnome-terminal desktop="^1" focus=on
bspc rule -a Steam desktop="^2"

feh --bg-scale ~/Pictures/desktop.png

panel &
