#! /bin/sh

# Please look in `man bspwm` for more details

# Start SXHKD Daemon
sxhkd &

# '\uf109' = 1: Terminal
# '\uf120' = 2: Terminal
# '\uf126' = 3: Code Fork
# '\uf1b6' = 4: Steam
# '\uf001' = 5: Music Icon
bspc monitor -d $(echo -e '\uf120') $(echo -e '\uf120') $(echo -e '\uf126') $(echo -e '\uf1b6') $(echo -e '\uf001')

# Node Settings:
# Int - Window Border Width
bspc config border_width         2

# Monitor/Desktop Settings:
# Int - Size of the gap that seperates windows
bspc config window_gap          12

# Global Settings
# Float - Default Split Ratio
bspc config split_ratio          0.5
# Bool - Remove borders of tiled windows for the monocle desktop layout
bspc config borderless_monocle   true
# Bool - Remove gaps of tiled windows for the monocle desktop layout
bspc config gapless_monocle      true
# RGB - Color of the border of an unfocused window
#   Dark Grey/Black
bspc config normal_border_color "#1e1e1e"
# RGB - Color of the border of a focused window on an unfocused monitor
#   Teal/Green
bspc config active_border_color "#2fd496"
# RGB - Color of the border of a focused window on a focused monitor
#   Teal/Green
bspc config focused_border_color "#2fd496"
# RGB - Color of the node --presel-{dir,ratio} message feedback area
#   White
bspc config presel_border_color "#ffffff"

# Rules
bspc rule -a gnome-terminal desktop="^1" focus=on
bspc rule -a Steam desktop="^2"

# Extra Junk
feh --bg-scale ~/Pictures/desktop.png

# Start "panel" (must be located in your PATH)
panel &
