#!/usr/bin/bash

# Script to tell us the amount of updates needed on the box (Slowly building to be platform agnostic, might add an opion to use "instance" and based on taht do the below
# Need to add menu on click to preform updates if wanted (would need to prompt for sudo)

URGENT_VALUE=25
OS_UBUNTU=`cat /etc/*release* | grep NAME=\"Ubuntu\" | wc -l` # Tested and works
OS_ARCH=`cat /etc/*release* | grep Arch`  # Untested please let me know if this has issues

if [[ $? -gt 0 ]]; then
  return
fi

if [ "$OS_UBUNTU" = "1" ]; then
    PACKAGES=$(/usr/lib/update-notifier/apt-check --human-readable | wc -l)
    UPDATES=`/usr/lib/update-notifier/apt-check --human-readable | awk 'FNR == 1 {print $1}'`
    if [ "$PACKAGES" -gt "1" ]; then
        SECURITY=`/usr/lib/update-notifier/apt-check --human-readable | awk 'FNR == 2 {print $1}'`
    fi
    # Echo the number of updates, and the number of security updates IF they exist
    echo "${UPDATES} Updates"
    if [ ! -z "$SECURITY" ]; then
        echo "${SECURITY} Security"
    fi
elif  [ $OS_ARCH = "0" ]; then
    PACKAGES=$(pacman -Qu)
    PACKAGE_COUNT=$(echo -n "${PACKAGES}" | wc -l)
    if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
      echo "${PACKAGE_COUNT}" # full-text
      echo "${PACKAGE_COUNT}" # short-text
      echo ""
      if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
        exit 33
      fi
    fi
else
    exit 10
fi
